### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by SuspiciouslyStickySock** [BenABaron/pf2e-level-up-wizard#3]
So far great module i love the idea! I do have a few suggestions

1. Please make this compatible with Free Archetype, i know this will most likely be very hard but please!!!

2. A way to filter feats, once you get to General, Skill or Class feats at a higher level the list becomes very long

**Comment by BenABaron** [comment]
Thank you for trying it out and for the suggestions! Replying to each of these:

1. This will definitely come in the future! Stay tuned :)
2. This is also something I'll be looking into, not sure of how difficult it will be to implement but I'm thinking level clamps (set min level) as well as adding different sorting options as suggested by others, namely alphabetically rather than by level. Long term think I could implement higher level filters like a search, but think that will be more involved.

**Comment by Gossetjr** [comment]
I came here to suggest the same about Free Archetype. Ha ha Glad I looked here before making my own "issue."

**Comment by BenABaron** [comment]
All of these features have been implemented! Gonna close this issue :)
